config/routes.rb
Rails.application.routes.draw do
  resources :tickets
  resources :car_users
  resources :spaces
  resources :parking_zones
  resources :cars
  resources :users
  root to: 'pages#home'
  get '/tickets/new/:parking_zone_id/:street_name', to: 'tickets#new', as: 'street_ticket'
  get "/sessions/new", to: "sessions#new", as: "new_session"
  post "/sessions", to: "sessions#create", as: "sessions"
  delete "/sessions", to: "sessions#destroy"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    has_many :car_users
    has_many :cars, through: :car_users
    validates_format_of :email, with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/
    validates :first_name, presence: :true
    validates :last_name, presence: :true
    validates :user_name, presence: :true, uniqueness: :true
    validates :password_digest, presence: :true
    has_secure_password

    def full_name
        self.first_name + ' ' + self.last_name
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize_user, only: [:show, :edit]
  before_action :users_profile?, only: [:show]
        
  

        def show
          @user = User.find(params[:id])
        end

        def new
          @user = User.new
        end

        def edit
          @user = User.find(params[:id])
        end

        def create
          @user = User.new(user_params)
          @user.save
          if @user.valid?
            session[:user_id] = @user.id
            redirect_to user_path(@user.id)
          else
            render :new
          end
        end

        def update
          @user = User.find(params[:id])
          @user.update(user_params)
          if @user.valid?
            redirect_to user_path(@user)
          else
            render :edit
          end
        end



        private

        def user_params
          params.require(:user).permit(:user_name, :first_name, :last_name, :email, :password)
        end

        def users_profile?
          unless User.find(params[:id]) == current_user
            flash[:notice] = "Unauthorized User Account"
            redirect_to user_path(current_user.id)
          end
        end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
  <div class="card border-0 shadow my-5">
    <div class="card-body p-5">


<body class = "text-center" data-gr-c-s-loaded= "true">

  <h1><%= "Hi, #{current_user.user_name}!"%></h1>
  <p class= "lead"> Please change any information you wish to update below:</p>

<% if @user.errors.full_messages.length > 0 %>
  <h2><%= pluralize(@user.errors.full_messages.length , "error") %> prohibited this car from being registered:</h2>
  <ul>
    <% @user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>


<%= form_for(@user) do |f| %>
  <table class = "center">
    <tbody>
      <tr>
        <td><%= f.label :username %></td>
        <td><%= f.text_field :user_name %></td>
      </tr>
      <tr>
        <td><%= f.label :first_name %></td>
        <td><%= f.text_field :first_name %></td>
      </tr>
      <tr>
        <td><%= f.label :last_name %></td>
        <td> <%= f.text_field :last_name %></td>
      </tr>
      <tr>
        <td><%= f.label :email %></td>
        <td><%= f.email_field :email %></td>
      </tr>
      <tr>
        <td><%= f.label :password %></td>
        <td><%= f.password_field :password %></td>
      </tr>
    </tbody>
  </table><br>
  <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small><br>
  <button type="submit" class="btn btn-danger text-uppercase ">Edit User</button>
  <% end %>
</body>


</div>
</div>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="card border-0 shadow my-5">
    <div class="card-body p-5">

<body class = "text-center" data-gr-c-s-loaded= "true">
<% if @user.errors.full_messages.length > 0 %>
  <h2><%= pluralize(@user.errors.full_messages.length , "error") %> prohibited this car from being registered:</h2>
  <ul>
    <% @user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<h1 class= "cover-heading"> Welcome to SnAppy!</h1>
<p class= "lead"> To find and purchase parking you will need to create an account</p>
<p class= "lead"> Please fill in the form below with your information:</p>


<%= form_for(@user) do |f| %>
  <table class = "center">
    <tbody>
      <tr>
        <td><%= f.label :username %></td>
        <td><%= f.text_field :user_name %></td>
      </tr>
      <tr>
        <td><%= f.label :first_name %></td>
        <td><%= f.text_field :first_name %></td>
      </tr>
      <tr>
        <td><%= f.label :last_name %></td>
        <td> <%= f.text_field :last_name %></td>
      </tr>
      <tr>
        <td><%= f.label :email %></td>
        <td><%= f.email_field :email %></td>
      </tr>
      <tr>
        <td><%= f.label :password %></td>
        <td><%= f.password_field :password %></td>
      </tr>
    </tbody>
  </table><br>
  <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small><br>
  <button type="submit" class="btn btn-danger text-uppercase " >Create User</button>
  <% end %>
  <br>
 <%= link_to '<button type="button" class="btn btn-danger text-uppercase ">Home</button>'.html_safe, root_path %>
</body>

</div>
</div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="card border-0 shadow my-5">
    <div class="card-body p-5">
      <h1>Welcome to SnAppy Parking!</h1>
<% if @user.car_users.count >= 1 %>
  <h3 class= "lead">You have registered the following cars:</h3>
  <h3 class= "lead">Select a car to see your tickets</h3>
    <ul>
      <table>
        <thead>
          <tr>
            <th col span="2" style="width: 75%"></th>
          </tr>
        </thead>
      
        <tbody>
          <% @user.car_users.each do |cu| %>
            <tr>
              
              <td><%= link_to cu.car.make, car_user_path(cu), class: "btn btn-danger"%></td>
              <td><%= link_to 'Destroy', cu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </ul>
  <% else %>
    <h4>You currently have no cars registered!</h4>
  <% end %>




<a class="btn btn-danger text-uppercase" href="/cars/new" role="button">Register a New Car</a>
<a class="btn btn-danger text-uppercase" href="/parking_zones" role="button">Find a Parking Space</a>



</div>
</div>
</div>