config/routes.rb
Rails.application.routes.draw do
  resources :tickets
  resources :car_users
  resources :spaces
  resources :parking_zones
  resources :cars
  resources :users
  root to: 'pages#home'
  get '/tickets/new/:parking_zone_id/:street_name', to: 'tickets#new', as: 'street_ticket'
  get "/sessions/new", to: "sessions#new", as: "new_session"
  post "/sessions", to: "sessions#create", as: "sessions"
  delete "/sessions", to: "sessions#destroy"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/car_user.rb
class CarUser < ApplicationRecord
    belongs_to :user 
    belongs_to :car
    has_many :tickets, dependent: :destroy
    has_many :spaces, through: :tickets

    def active_tickets
       arr = self.tickets.where(active: true)
        arr.order("(created_at) DESC")
    end

    def expired_tickets
      arr = self.tickets.where(active: false)
        arr.order('created_at DESC').take(5) 
    end
end

app/controllers/car_users_controller.rb
class CarUsersController < ApplicationController
    before_action :authorize_user, only: [:show, :destroy]

    def show
        @car_user = CarUser.find(params[:id])   
    end 


    def destroy
        CarUser.destroy(params[:id])
        redirect_to user_path(current_user.id)
    end

end

app/helpers/car_users_helper.rb
module CarUsersHelper
end

app/views/car_users/show.html.erb
<div class="container">
    <div class="card border-0 shadow my-5">
      <div class="card-body p-5">
<h1>Car Information:</h1>
    <ul>
        <li> Make: <%=@car_user.car.make%></li>
        <li> Model: <%=@car_user.car.model%></li>
        <li> Colour: <%=@car_user.car.colour%></li>
        <li> Registration Plate: <%=@car_user.car.registration_plate%></li>
    </ul>
        <% if @car_user.tickets.count >= 1 %>

    <h3 class = "orange" >Active Tickets:</h3>
        <ul>
            <% @car_user.active_tickets.each do |ticket| %>
                <li><%= link_to "#{ticket.space.street_name}, Purchased - #{ticket.created_at.strftime("%B %d, %Y at %H:%M")}", ticket_path(ticket.id) %></li>
            <%end%>
        </ul>


    <h3 class = "orange">Recently Expired Tickets:</h3>
            <ul>
                <% @car_user.expired_tickets.each do |ticket| %>
                    <li><%= link_to "#{ticket.space.street_name}, Purchased - #{ticket.created_at.strftime("%B %d, %Y at %H:%M")}, Expired - #{ticket.expiration.strftime("%B %d, %Y at %H:%M")}", ticket_path(ticket.id) %></li>
                <%end%>
            </ul>
        <% else %>
            <h3><%= "You have no recent tickets" %></h3>
        <% end %>
        <br>    


 <%= link_to '<button type="button" class="btn btn-danger text-uppercase ">Back</button>'.html_safe, user_path(current_user) %>
 <%= link_to '<button type="button" class="btn btn-danger text-uppercase ">Purchase a ticket</button>'.html_safe, parking_zones_path %>

</div>
</div>
</div>