config/routes.rb
Rails.application.routes.draw do
  resources :tickets
  resources :car_users
  resources :spaces
  resources :parking_zones
  resources :cars
  resources :users
  root to: 'pages#home'
  get '/tickets/new/:parking_zone_id/:street_name', to: 'tickets#new', as: 'street_ticket'
  get "/sessions/new", to: "sessions#new", as: "new_session"
  post "/sessions", to: "sessions#create", as: "sessions"
  delete "/sessions", to: "sessions#destroy"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/parking_zone.rb
class ParkingZone < ApplicationRecord
    has_many :spaces

    def available_space
    end

    def unique_street_names
        # self.spaces.map { |space| space.street_name }.uniq
        self.spaces.group(:street_name)

    end
end

app/controllers/parking_zones_controller.rb
class ParkingZonesController < ApplicationController
    before_action :authorize_user, only: [:index, :show]
    before_action :user_cars?, only: [:index, :show]
    
    def index
        @parking_zones = ParkingZone.all
    end
    
    def show
        @parking_zone = ParkingZone.find(params[:id])
    end
end

app/helpers/parking_zones_helper.rb
module ParkingZonesHelper
end

app/views/parking_zones/index.html.erb
<div class="container">
  <div class="card border-0 shadow my-5">
    <div class="card-body p-5">

<h1 class= "cover-heading text-center">Parking Zones</h1>
<p class= "lead">Select a Parking zone:</p>
<ul>
    <% @parking_zones.each do |parking_zone| %>
      <li class="text-danger"><%= link_to parking_zone.area_name, parking_zone %></li>  
    <% end %>
  </ul>
  <%= link_to '<button type="button" class="btn btn-danger text-uppercase ">Back</button>'.html_safe, user_path(current_user.id) %>
  


</div>
</div>
</div>

app/views/parking_zones/show.html.erb
<div class="container">
    <div class="card border-0 shadow my-5">
      <div class="card-body p-5">
<h2 class= "cover-heading" style="color:rgb(255, 115, 0)" >You are looking at streets in <%= @parking_zone.area_name %>:</h2>
<p class= "lead">Street Name:</p>
<div class="tableFixHead table table-striped">
<table>
 <thead>
    <tr>
      <th >Street Name</th>
      <th class="text-center" >Spaces Available</th>
    </tr>
  </thead>
<tbody>
        <% @parking_zone.unique_street_names.each do |street|%>
        <tr>
            <td><%= link_to street.street_name, street_ticket_path(:parking_zone_id => street.parking_zone_id, :street_name => street.street_name) %></td>
            <td class="text-center"><%= street.number_active_spaces %></td> 
        </tr>
            
            <% end %>
        
    </tbody>
</table>
</div>
        <%= link_to '<button type="button" class="btn btn-danger text-uppercase ">Back</button>'.html_safe, parking_zones_path %>
</div>
</div>
</div>

        
   