config/routes.rb
Rails.application.routes.draw do
  resources :tickets
  resources :car_users
  resources :spaces
  resources :parking_zones
  resources :cars
  resources :users
  root to: 'pages#home'
  get '/tickets/new/:parking_zone_id/:street_name', to: 'tickets#new', as: 'street_ticket'
  get "/sessions/new", to: "sessions#new", as: "new_session"
  post "/sessions", to: "sessions#create", as: "sessions"
  delete "/sessions", to: "sessions#destroy"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
    has_many :car_users
    has_many :users, through: :car_users
    validates_format_of :registration_plate, { with: /(^[A-Z]{2}[0-9]{2} [A-Z]{3}$)/, message: "Invalid Registration Plate - Corret Format \"AA11 AAA\" " }
    validates :model, presence: :true
    validates :make, presence: :true
    validates :colour, presence: :true
end

app/models/car_user.rb
class CarUser < ApplicationRecord
    belongs_to :user 
    belongs_to :car
    has_many :tickets, dependent: :destroy
    has_many :spaces, through: :tickets

    def active_tickets
       arr = self.tickets.where(active: true)
        arr.order("(created_at) DESC")
    end

    def expired_tickets
      arr = self.tickets.where(active: false)
        arr.order('created_at DESC').take(5) 
    end
end

app/models/parking_zone.rb
class ParkingZone < ApplicationRecord
    has_many :spaces

    def available_space
    end

    def unique_street_names
        # self.spaces.map { |space| space.street_name }.uniq
        self.spaces.group(:street_name)

    end
end

app/models/space.rb
class Space < ApplicationRecord
    belongs_to :parking_zone
    has_many :tickets
    has_many :car_users, through: :tickets


    def number_active_spaces
        total = 0
        arr = Space.where(street_name: self.street_name)
        arr.map do |space|
        arr2 = space.tickets
        total += arr2.select { |ticket| ticket.active == true }.count
        end
        arr.count - total
    end

    def self.available_spaces(array)
        space_instance = []
        array.each do |space|
            if space.tickets.empty?
                space_instance << space
            elsif space.tickets.select { |ticket| ticket.active == true }.empty?
                space_instance << space
            end
        end
        space_instance
    end


   

end

app/models/ticket.rb
class Ticket < ApplicationRecord
    belongs_to :car_user
    belongs_to :space

    validates :hours_purchased, presence: :true
    

    def expiration
        self.created_at + self.hours_purchased.hours
    end

    def user 
        self.car_user.user
    end

    def car
        self.car_user.car
    end

    def ticket_amount
        self.space.parking_zone.tariff_per_hour * self.hours_purchased
    end


end

app/models/user.rb
class User < ApplicationRecord
    has_many :car_users
    has_many :cars, through: :car_users
    validates_format_of :email, with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/
    validates :first_name, presence: :true
    validates :last_name, presence: :true
    validates :user_name, presence: :true, uniqueness: :true
    validates :password_digest, presence: :true
    has_secure_password

    def full_name
        self.first_name + ' ' + self.last_name
    end

end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
    before_action :authorize_user, only: [:new, :create]

    def new
    @car = Car.new
    end

    def create
        @car = Car.find_by(registration_plate: params[:car][:registration_plate])
        if @car
            @car_user = CarUser.create(car_id: @car.id, user_id: current_user.id)
            redirect_to car_user_path(@car_user.id)
        else
        @car = Car.new(car_params)
        @car.save
        if @car.valid?
        @car_user = CarUser.create(car_id: @car.id, user_id: current_user.id)
        redirect_to car_user_path(@car_user.id)
        else
            render :new
        end
    end
end


    private

    def car_params
        params.require(:car).permit(:make, :model, :colour, :registration_plate)
      end

    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end
  end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :authorize_user, only: [:show, :new, :create]
    before_action :create_new_ticket?, only: [:new] 


    def show
        @ticket = Ticket.find(params[:id])
    end
    
    def new
        @ticket = Ticket.new
        all_spaces = Space.where(street_name: params[:street_name])
        @available_spaces = Space.available_spaces(all_spaces)
        @space = @available_spaces.first
        @user = User.find(current_user.id)
    end
  
    def create
        @car_user = CarUser.find_by(car_id: params[:car][:car_id], user_id: session[:user_id])
        @ticket = Ticket.create(car_user_id: @car_user.id, space_id: params[:ticket][:space_id], hours_purchased: params[:ticket][:hours_purchased], active: true)
        redirect_to ticket_path(@ticket.id)
        
    end


    private


    def ticket_params
        params.require(:ticket).permit(:hours_purchased, :car_id, :space_id)
      end


    def create_new_ticket?
        all_spaces = Space.where(street_name: params[:street_name])
        @available_spaces = Space.available_spaces(all_spaces)
        if @available_spaces.empty?
          flash[:notice] = "Sorry, there are no available spaces at this time."
          redirect_to parking_zone_path(params[:parking_zone_id])
        end
      end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize_user, only: [:show, :edit]
  before_action :users_profile?, only: [:show]
        
  

        def show
          @user = User.find(params[:id])
        end

        def new
          @user = User.new
        end

        def edit
          @user = User.find(params[:id])
        end

        def create
          @user = User.new(user_params)
          @user.save
          if @user.valid?
            session[:user_id] = @user.id
            redirect_to user_path(@user.id)
          else
            render :new
          end
        end

        def update
          @user = User.find(params[:id])
          @user.update(user_params)
          if @user.valid?
            redirect_to user_path(@user)
          else
            render :edit
          end
        end



        private

        def user_params
          params.require(:user).permit(:user_name, :first_name, :last_name, :email, :password)
        end

        def users_profile?
          unless User.find(params[:id]) == current_user
            flash[:notice] = "Unauthorized User Account"
            redirect_to user_path(current_user.id)
          end
        end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/car_spaces_helper.rb
module CarSpacesHelper
end

app/helpers/car_users_helper.rb
module CarUsersHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/parking_zones_helper.rb
module ParkingZonesHelper
end

app/helpers/spaces_helper.rb
module SpacesHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title >SnAppy Parking</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>
  
    <% if flash[:notice] %>
      <div class="alert alert-danger" role="alert">
        <%= flash[:notice]%>
      </div>  
    <% end %>





      <nav class="navbar navbar-expand-lg sticky-top navbar-dark bg-dark menu-area">
        <%= link_to image_tag("logo1.png", alt: "logo", size: "140x40"), '/', class: 'navbar-brand' %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
              <div class="navbar-nav" style="color: white">
     <% if current_user %>
                <a style="color: white" class="nav-item nav-link" <%= link_to "Hi, #{current_user.user_name}!" , user_path(current_user.id) %></a>
                <a style="color: white" class="nav-item nav-link" <%= link_to 'Purchase a ticket', parking_zones_path %></a>
                <a style="color: white" class="nav-item nav-link" <%= link_to 'Edit User', edit_user_path(current_user.id)%></a>
                <a style="color: white" class="nav-item nav-link" <%= link_to "Register Car", new_car_path %></a>
                <a style="color: white" class="nav-item nav-link" <%= link_to "Logout", sessions_path, method: :delete %></a>
              </div>
          </div>

      </nav>
    <% else %>
      
                <a style="color: white" class="nav-item nav-link" <%= link_to "Login", new_session_path %></a>
                <a style="color: white" class="nav-item nav-link" <%= link_to "Create a New User", new_user_path %></a>
              </div>
          </div>
      </nav>  
    <% end %>
    <%= yield %>
  </body >
  
</html>

app/views/pages/home.html.erb
<div class="container">
    <div class="card border-0 shadow my-5">
      <div class="card-body p-5">

<body class = "text-center" data-gr-c-s-loaded= "true">
<h1 class= "cover-heading">Welcome to SnAppy Parking!</h1>

<p class= "lead">Find parking in the Borough of Camden</p>
<p class=>Choose from thousands of spaces in Camden, with access to an unrivalled choice of the best spaces.</p>
<p class=>We’re parking obsessed. It began when we launched SnAppyParking, the tool that makes parking easy for everyone. By working so closely with the Camden Local Authorities, we realised the huge, untapped potential lying right under all of our feet.  </p>
<p>From our early days helping drivers park on driveways around sports stadiums to where we are now, helping drivers park across over 3,000 locations in the borough of Camden – SnAppy is now one of the most loved parking apps.</p>
<p>We make parking easy for drivers – We offer on-street and off-street parking options </p>
<p class=>Click to <%= link_to 'reserve', parking_zones_path %>  a guaranteed space. Trusted by over 3 million drivers across the UK.</p>

<%= image_tag "map.png", :class => "img-fluid", size: "800x800  ", alt: "Camden Map" %>



</body>


</div>
</div>
</div>